// PAGE ACTION TYPES
export const LOAD_COMPLETE = "LOAD_COMPLETE";
export const UPDATE_THEME = "UPDATE_THEME";

// WATCHIO ACTION TYPES
export const GET_MOVIES_GROUP = "GET_MOVIES_GROUP";
export const GET_SERIALS_GROUP = "GET_SERIALS_GROUP";
export const GET_ANIME_GROUP = "GET_ANIME_GROUP";
export const ADD_ANIME_GROUP = "ADD_ANIME_GROUP";
export const ADD_SERIAL_GROUP = "ADD_SERIAL_GROUP";
export const ADD_MOVIE_GROUP = "ADD_MOVIE_GROUP";
export const DELETE_ANIME_GROUP = "DELETE_ANIME_GROUP";
export const DELETE_SERIAL_GROUP = "DELETE_SERIAL_GROUP";
export const DELETE_MOVIE_GROUP = "DELETE_MOVIE_GROUP";
export const GET_WATCHIO_INFO = "GET_WATCHIO_INFO";

// POSTERS ACTION TYPES
export const ADD_POSTER = "ADD_POSTER";
export const ADD_ANIME_POSTER = "ADD_ANIME_POSTER";
export const ADD_SERIAL_POSTER = "ADD_SERIAL_POSTER";
export const ADD_MOVIE_POSTER = "ADD_MOVIE_POSTER";
export const UPDATE_POSTER = "UPDATE_POSTER";
export const UPDATE_ANIME_POSTER = "UPDATE_ANIME_POSTER";
export const UPDATE_SERIAL_POSTER = "UPDATE_SERIAL_POSTER";
export const UPDATE_MOVIE_POSTER = "UPDATE_MOVIE_POSTER";
export const DELETE_POSTER = "DELETE_POSTER";
export const DELETE_ANIME_POSTER = "DELETE_ANIME_POSTER";
export const DELETE_SERIAL_POSTER = "DELETE_SERIAL_POSTER";
export const DELETE_MOVIE_POSTER = "DELETE_MOVIE_POSTER";
