// PAGE ACTION TYPES
export const LOAD_COMPLETE = "LOAD_COMPLETE";
export const UPDATE_THEME = "UPDATE_THEME";

// WATCHIO ACTION TYPES
export const GET_GROUPS = "GET_GROUPS";
export const GET_MOVIE_GROUPS = "GET_MOVIE_GROUPS";
export const GET_SERIAL_GROUPS = "GET_SERIAL_GROUPS";
export const GET_ANIME_GROUPS = "GET_ANIME_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const ADD_ANIME_GROUP = "ADD_ANIME_GROUP";
export const ADD_SERIAL_GROUP = "ADD_SERIAL_GROUP";
export const ADD_MOVIE_GROUP = "ADD_MOVIE_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const UPDATE_ANIME_GROUP = "UPDATE_ANIME_GROUP";
export const UPDATE_SERIAL_GROUP = "UPDATE_SERIAL_GROUP";
export const UPDATE_MOVIE_GROUP = "UPDATE_MOVIE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_ANIME_GROUP = "DELETE_ANIME_GROUP";
export const DELETE_SERIAL_GROUP = "DELETE_SERIAL_GROUP";
export const DELETE_MOVIE_GROUP = "DELETE_MOVIE_GROUP";

export const ADD_VIDEO = "ADD_VIDEO";
export const ADD_ANIME_VIDEO = "ADD_ANIME_VIDEO";
export const ADD_SERIAL_VIDEO = "ADD_SERIAL_VIDEO";
export const ADD_MOVIE_VIDEO = "ADD_MOVIE_VIDEO";
export const UPDATE_VIDEO = "UPDATE_VIDEO";
export const UPDATE_ANIME_VIDEO = "UPDATE_ANIME_VIDEO";
export const UPDATE_SERIAL_VIDEO = "UPDATE_SERIAL_VIDEO";
export const UPDATE_MOVIE_VIDEO = "UPDATE_MOVIE_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_ANIME_VIDEO = "DELETE_ANIME_VIDEO";
export const DELETE_SERIAL_VIDEO = "DELETE_SERIAL_VIDEO";
export const DELETE_MOVIE_VIDEO = "DELETE_MOVIE_VIDEO";

export const GET_WATCHIO_INFO = "GET_WATCHIO_INFO";

// POSTERS ACTION TYPES
export const ADD_POSTER = "ADD_POSTER";
export const ADD_ANIME_POSTER = "ADD_ANIME_POSTER";
export const ADD_SERIAL_POSTER = "ADD_SERIAL_POSTER";
export const ADD_MOVIE_POSTER = "ADD_MOVIE_POSTER";
export const UPDATE_POSTER = "UPDATE_POSTER";
export const UPDATE_ANIME_POSTER = "UPDATE_ANIME_POSTER";
export const UPDATE_SERIAL_POSTER = "UPDATE_SERIAL_POSTER";
export const UPDATE_MOVIE_POSTER = "UPDATE_MOVIE_POSTER";
export const DELETE_POSTER = "DELETE_POSTER";
export const DELETE_ANIME_POSTER = "DELETE_ANIME_POSTER";
export const DELETE_SERIAL_POSTER = "DELETE_SERIAL_POSTER";
export const DELETE_MOVIE_POSTER = "DELETE_MOVIE_POSTER";

// ITEMS FILTERS ACTION TYPES
export const UPDATE_WATCHIO_FILTER = "UPDATE_WATCHIO_FILTER";

// MODAL ACTION TYPE
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
